version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - migrations
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
      ports:
        - "1431:1431"
        - "1432:1432"
        - "1433:1433"
      expose:
        - "1433"
      depends_on:
        - migrations
  migrations:
    build:
      context: .
      dockerfile: Migrations.Dockerfile

# "DefaultConnection": "Server=localhost;Database=Movie;User Id=sa;password=Password123!;Trusted_Connection=False;"
